## PyTorchの特徴
### 利点
- 学習用データの取り込みなど、機能が豊富で拡張性が高い
- 必要に応じて独自の機能を簡単に開発しやすい
### 欠点
- 機械学習モデルの定義方法などがやや複雑で敷居が高い
- Kerasなら関数(fit)１つで実装できる、機械学習モデルの学習処理を、自ら記述する必要がある 

In [3]:
import torch
import numpy as np
#device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
#!git clone https://github.com/makaishi2/pythonlibs.git

In [4]:
r0 = torch.tensor(1.0).float()
print(type(r0))
print(r0.dtype)
print(r0.shape)
print(r0.data)

<class 'torch.Tensor'>
torch.float32
torch.Size([])
tensor(1.)


In [5]:
r1_np = np.array([1,2,3,4,5])
print(r1_np.shape)

r1 = torch.tensor(r1_np).float()
print(r1.dtype)
print(r1.shape)
print(r1.data)

(5,)
torch.float32
torch.Size([5])
tensor([1., 2., 3., 4., 5.])


In [6]:
r2_np = np.array([[1,5,6],[4,3,2]])
print(r2_np.shape)

r2 = torch.tensor(r2_np).float()
print(r2.dtype)
print(r2.shape)
print(r2.data)

(2, 3)
torch.float32
torch.Size([2, 3])
tensor([[1., 5., 6.],
        [4., 3., 2.]])


In [7]:
torch.manual_seed(123)
r3 = torch.randn((3,2,2))
print(r3.shape)
print(r3.data)

torch.Size([3, 2, 2])
tensor([[[-0.1115,  0.1204],
         [-0.3696, -0.2404]],

        [[-1.1969,  0.2093],
         [-0.9724, -0.7550]],

        [[ 0.3239, -0.1085],
         [ 0.2103, -0.3908]]])


In [8]:
r4 = torch.ones((2,3,2,2))
print(r4.shape)
print(r4.data)

torch.Size([2, 3, 2, 2])
tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])


In [9]:
r5 = r1.long()
print(r5.dtype)
print(r5)

torch.int64
tensor([1, 2, 3, 4, 5])


In [11]:
print(r3)
r6 = r3.view(3, -1) #reshapeと同じ
print(r6.shape)
print(r6.data)

tensor([[[-0.1115,  0.1204],
         [-0.3696, -0.2404]],

        [[-1.1969,  0.2093],
         [-0.9724, -0.7550]],

        [[ 0.3239, -0.1085],
         [ 0.2103, -0.3908]]])
torch.Size([3, 4])
tensor([[-0.1115,  0.1204, -0.3696, -0.2404],
        [-1.1969,  0.2093, -0.9724, -0.7550],
        [ 0.3239, -0.1085,  0.2103, -0.3908]])


In [12]:
print(r3)
r7 = r3.view(-1) #reshapeと同じ
print(r7.shape)
print(r7.data)

tensor([[[-0.1115,  0.1204],
         [-0.3696, -0.2404]],

        [[-1.1969,  0.2093],
         [-0.9724, -0.7550]],

        [[ 0.3239, -0.1085],
         [ 0.2103, -0.3908]]])
torch.Size([12])
tensor([-0.1115,  0.1204, -0.3696, -0.2404, -1.1969,  0.2093, -0.9724, -0.7550,
         0.3239, -0.1085,  0.2103, -0.3908])
